#!/usr/bin/env bash
# displays "To infinity and beyond" indefinit with
# sleep 2 in between each iteration
# thwn display "I am invincible!!!" in between each iteration.

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
