#!/usr/bin/env bash
# nginx running as nginx user
# nginx listening on all active IPs on port 8080

sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
